### ISSUE TITLE
there is no data on sobigdata

### ISSUE THREAD

**Issue by Sandy4321** [jeannetm/predict_influenza_with_retail_records#1]
there is no data on sobigdata

https://sobigdata.d4science.org/catalogue-sobigdata?path=/dataset/retail_market_data

![image](https://user-images.githubusercontent.com/11426119/103586489-2dd55400-4eb3-11eb-8a4b-f04a087105fc.png)

**Comment by jeannetm** [comment]
Dear Sandy4321, as we mention in the COOP_README file, due to privacy and confidentiality reasons the access is only on-site visit. So if you are interested in the data, please write an email to one of the contributors and you can find an adequate solution.
